### PR TITLE
fix: installs failing on arm architecture

### LINKED ISSUE #34: Flutter orb install_sdk does not work on Apple silicon M1 macs
## What happened:
When installing flutter sdk using the flutter orb on M1 mac, flutter doctor throws the following error:
```
/Users/distiller/development/flutter/bin/internal/shared.sh: line 239: /Users/distiller/development/flutter/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable
```
I assume this is caused by downloading the wrong CPU architecture SDK - amd64 instead of arm64.

## Expected behavior:

Flutter orb downloads sdk without any problems on M1 macs and without any need to specify CPU architecture.

### Minimal example config.yaml to reproduce the error:

``` YAML
version: 2.1

orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  example:
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: 15.0.0
    steps:
      - flutter/install_sdk:
          version: 3.13.4
```

## Workaround
Prepend the flutter version with `arm64_` like this:
``` YAML
steps:
  - flutter/install_sdk:
      version: arm64_3.13.5
```

### PR DESCRIPTION
**Pull request by ryanbourdais**
Added a conditional for checking arm architecture to the install script, this should close #34

### CODE REVIEW

File: src/scripts/install-sdk.sh [hunk 1]
```diff
@@ -5,11 +5,21 @@ INSTALL_LOCATION=$(eval "echo $ORB_EVAL_INSTALL_LOCATION")
 if [ ! -d "$INSTALL_LOCATION/flutter" ]; then
   mkdir -p "$INSTALL_LOCATION"
   if [ "$(uname)" == 'Darwin' ]; then
-    curl -o flutter_sdk.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_$ORB_VAL_FLUTTER_SDK_VERSION-stable.zip
+    if [ "$(uname -m)" == "arm64" ]; then
```
Comment (JalexChen) [inline src/scripts/install-sdk.sh:8]: i'm wondering if it might be better to just use a function to replace all the if/else/elif.

maybe something like this would be easier to read, with the install defaulting to Linux/amd64

function install_flutter() {
  local machine=${1:-"Linux"}
  local arch=${2:-"amd64"}
  [[ $machine == "Darwin" ]] && uname=macos || uname=linux
  [[ $arch == "arm64" ]] && version="${uname}_arm64" || version="${uname}"
  [[ $uname == "linux" ]] && suffix="tar.xz" || suffix="zip"

  baseurl="https://storage.googleapis.com/flutter_infra_release/releases/stable"

  [[ $arch == "arm64" ]] && version="flutter_${uname}_arm64" || version="flutter_${uname}"

  fullurl="$baseurl/$uname/${version}_$ORB_VAL_FLUTTER_SK_VERSION-stable.${suffix}"

  curl -o "flutter_sdk.${suffix}" "$fullurl"
}

install_flutter "$(uname)" "$(uname -a)"
# mac arm64
# https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_-stable.zip

install_flutter
# https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_-stable.tar.xz

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:a874dbfd973f09ace7f8abd6a25887a51a22bc26

**Review by JalexChen — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:b473172d318fb10def77644e0b8cace70c2acd6a

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/flutter?version=dev:b473172d318fb10def77644e0b8cace70c2acd6a

File: src/scripts/install-sdk.sh [hunk 2]
```diff
@@ -2,21 +2,21 @@
...
+function install_flutter() {
+  local machine=${1:-"Linux"}
+  local arch=${2:-"amd64"}
+  [[ $machine == "Darwin" ]] && uname=macos || uname=linux
+  [[ $arch == "arm64" ]] && version="flutter_${uname}_arm64" || version="flutter_${uname}"
+  [[ $uname == "linux" ]] && suffix="tar.xz" || suffix="zip"
+
+  baseurl="https://storage.googleapis.com/flutter_infra_release/releases/stable"
+
+  fullurl="$baseurl/$uname/${version}_$ORB_VAL_FLUTTER_SK_VERSION-stable.${suffix}"
```
Comment (KevinJ1008) [inline src/scripts/install-sdk.sh:14]: Should be `ORB_VAL_FLUTTER_SDK_VERSION`
